/**
 * Lucide icon aliases matching the MUI icon names used throughout the app.
 * Import from here instead of @mui/icons-material.
 */
export {
  Download,
  CheckCircle,
  CheckCircle2 as CheckCircleOutline,
  Trash2 as Delete,
  Settings,
  Ban as Block,
  Info,
  HardDrive as Storage,
  Plus as Add,
  AlertTriangle as WarningAmber,
  AlertTriangle as Warning,
  Library as VideoLibrary,
  RefreshCw as Refresh,
  Clock as AccessTime,
  Shield as EighteenUpRating,
  Folder,
  ChevronDown as ExpandMore,
  ChevronDown,
  ChevronUp as ExpandLess,
  ChevronUp,
  Lock,
  Calendar as Schedule,
  AlertCircle as ErrorOutline,
  AlertCircle as Error,
  ListFilter as FilterList,
  Search,
  Filter as FilterAlt,
  Save,
  CalendarDays as CalendarToday,
  X as Clear,
  X as Close,
  CloudOff,
  Sparkles as NewReleases,
  AlarmCheck as AlarmOn,
  HelpCircle as HelpOutline,
  ArrowUp as ArrowUpward,
  ArrowDown as ArrowDownward,
  LayoutGrid as TableChart,
  List as ViewList,
  Video as Videocam,
  Video as VideoIcon,
  Copy as ContentCopy,
  XCircle as Cancel,
  Film as MovieOutlined,
  Music as AudiotrackOutlined,
  Music as AudioIcon,
  FileDown as FileDownload,
  StopCircle as Stop,
  ArrowDownAZ as SortByAlpha,
  MoreVertical as MoreVert,
  MoreHorizontal,
  Edit2 as Edit,
  Star,
  StarOff,
  Eye,
  EyeOff,
  Loader2,
  Check,
  ChevronRight,
  ChevronLeft,
  ChevronsLeft,
  ChevronsRight,
  ExternalLink,
  Link2 as Link,
  Upload,
  Image,
  FileText,
  FileVideo,
  Hash,
  Tag,
  Tags,
  Clock3 as Timer,
  Gauge,
  Wifi,
  WifiOff,
  Server,
  Database,
  Key,
  Bell,
  BellOff,
  User,
  Users,
  LogOut,
  LogIn,
  Shield,
  ShieldCheck,
  ShieldAlert,
  Home,
  Menu,
  Sidebar,
  PanelLeft,
  Columns2 as Columns,
  Rows2 as Rows,
  LayoutDashboard,
  Calendar,
  Globe,
  Map,
  Package,
  PackageOpen,
  Zap,
  ZapOff,
  Volume2,
  VolumeX,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Maximize,
  Minimize,
  Expand,
  Shrink,
  RotateCcw,
  RotateCw,
  Moon,
  Sun,
  Monitor,
  Smartphone,
  Tablet,
  Code,
  Terminal,
  Command,
  Keyboard,
  Mouse,
  Printer,
  Bookmark,
  BookmarkPlus,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Share,
  Share2,
  Github,
  Twitter,
  Linkedin,
  // Direct exports (used without alias in some components)
  Trash2,
  Ban,
  X,
  ListFilter,
  LayoutGrid,
  XCircle,
  Copy,
  Filter,
  ListChecks,
  List,
  RefreshCw,
  Plus,
  FolderX,
} from 'lucide-react';
