import React from 'react';
import { ThemeDefinition } from './types';

export const linearTheme: ThemeDefinition = {
  id: 'linear',
  name: 'Dark Modern',
  description: 'Deep atmosphere, precision depth, and ambient lighting pools.',
  layoutMode: 'top-nav',
  layout: {
    desktop: {
      navPlacement: 'top',
      headerFrameMode: 'flush',
      mobileHeaderInset: false,
      showHeaderToggleOnMobile: false,
      showDesktopNavItems: true,
      showStorageHeaderWidget: true,
      headerVersionPlacement: 'desktop',
      headerTitleInset: '12px',
      headerToggleMode: 'menu',
      headerToggleWidth: '44px',
      headerToggleHeight: '44px',
      headerToggleRadius: 'var(--radius-ui)',
      headerToggleColor: '#FFFFFF',
      headerUpdateIndicatorMode: 'linear',
      headerBackground: 'rgba(5, 5, 6, 0.72)',
      headerBorder: 'none',
      headerBorderBottom: '1px solid rgba(255, 255, 255, 0.1)',
      headerPattern: 'none',
      headerBackdropFilter: 'none',
      headerBorderRadius: '0px',
      headerMenuRadius: '12px',
      headerMenuBorder: '1px solid rgba(255, 255, 255, 0.1)',
      headerMenuBackground: '#09090b',
      headerMenuShadow: '0 10px 40px rgba(0,0,0,0.5)',
      shellBackground: '#050506',
      mainPadding: '32px 32px 48px',
      mainMarginTop: '64px',
      contentPadding: '24px 32px',
      contentMaxWidth: '1400px',
      contentMarginInline: 'auto',
      contentFrameBackground: 'transparent',
      contentFrameBorder: 'none',
      contentFrameRadius: '0px',
      contentFrameShadow: 'none',
    },
    mobile: {
      navPlacement: 'top',
      headerFrameMode: 'flush',
      mobileHeaderInset: false,
      showHeaderToggleOnMobile: true,
      showDesktopNavItems: false,
      showStorageHeaderWidget: false,
      headerVersionPlacement: 'mobile',
      headerTitleInset: '0px',
      headerToggleMode: 'menu',
      headerToggleWidth: '44px',
      headerToggleHeight: '44px',
      headerToggleRadius: 'var(--radius-ui)',
      headerToggleColor: '#FFFFFF',
      headerUpdateIndicatorMode: 'linear',
      headerBackground: 'rgba(5, 5, 6, 0.72)',
      headerBorder: 'none',
      headerBorderBottom: '1px solid rgba(255, 255, 255, 0.1)',
      headerPattern: 'none',
      headerBackdropFilter: 'none',
      headerBorderRadius: '0px',
      headerMenuRadius: '12px',
      headerMenuBorder: '1px solid rgba(255, 255, 255, 0.1)',
      headerMenuBackground: '#09090b',
      headerMenuShadow: '0 10px 40px rgba(0,0,0,0.5)',
      shellBackground: '#050506',
      mainPadding: '8px 8px calc(20px + env(safe-area-inset-bottom))',
      mainMarginTop: '64px',
      contentPadding: '12px 8px',
      contentMaxWidth: '1400px',
      contentMarginInline: 'auto',
      contentFrameBackground: 'transparent',
      contentFrameBorder: 'none',
      contentFrameRadius: '0px',
      contentFrameShadow: 'none',
    },
  },
  preview: React.createElement('div', {
    key: 'preview-root',
    style: {
      padding: '20px',
      borderRadius: '12px',
      backgroundColor: '#050506',
      border: '1px solid rgba(255, 255, 255, 0.1)',
      boxShadow: '0 8px 32px rgba(0, 0, 0, 0.8)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      overflow: 'hidden',
      position: 'relative',
      width: '100%',
      minHeight: 80,
    }
  }, [
    React.createElement('div', {
      key: 'b1',
      style: {
        position: 'absolute',
        top: -10,
        right: -10,
        width: 60,
        height: 60,
        borderRadius: '50%',
        background: 'radial-gradient(circle, rgba(94, 106, 210, 0.3) 0%, transparent 70%)',
        filter: 'blur(5px)',
      }
    }),
    React.createElement('div', {
      key: 'b2',
      style: { width: 44, height: 44, borderRadius: '6px', backgroundColor: '#5E6AD2', boxShadow: '0 0 15px rgba(94, 106, 210, 0.4)' }
    }),
    React.createElement('div', {
      key: 'b3',
      style: { width: 90, height: 16, borderRadius: '9999px', backgroundColor: 'rgba(255, 255, 255, 0.15)' }
    })
  ]),
  tokens: {
    light: {
      'font-body': "'Plus Jakarta Sans'",
      'font-display': "'Plus Jakarta Sans'",
      background: '240 10% 3.9%', // Dark by default for linear
      foreground: '0 0% 98%',
      card: '240 10% 3.9%',
      'card-foreground': '0 0% 98%',
      popover: '240 10% 3.9%',
      'popover-foreground': '0 0% 98%',
      primary: '235 56% 59%', // #5E6AD2
      'primary-foreground': '0 0% 100%',
      secondary: '142 72% 45%',
      'secondary-foreground': '0 0% 10%',
      muted: '240 3.7% 15.9%',
      'muted-foreground': '240 5% 64.9%',
      accent: '38 92% 55%',
      'accent-foreground': '0 0% 10%',
      destructive: '0 72% 50%',
      'destructive-foreground': '0 0% 98%',
      'success': '142 60% 45%',
      'success-foreground': '0 0% 98%',
      'warning': '38 90% 55%',
      'warning-foreground': '0 0% 10%',
      'info': '200 85% 55%',
      'info-foreground': '0 0% 10%',
      border: '240 3.7% 15.9%',
      'border-strong': '240 5% 30%',
      input: '240 3.7% 15.9%',
      'input-border': '240 3.7% 15.9%',
      'input-border-hover': '235 56% 59%',
      ring: '235 56% 59%',
      radius: '0.125rem', // 2px
      'radius-ui': '2px',
      'radius-input': '2px',
      'radius-thumb': '2px',
      'border-weight': '1px',
      'nav-radius': '0px',
      'action-bar-gap': '6px',
      'action-bar-gap-compact': '6px',
      'action-bar-padding-y': '8px',
      'action-bar-padding-x': '0px',
      'action-bar-foreground': '0 0% 98%',
      'action-bar-border': '240 3.7% 15.9%',
      'action-bar-hover-border': '240 5% 30%',
      'action-bar-disabled-foreground': '240 5% 64.9%',
      'fab-primary-bg': 'var(--primary)',
      'fab-primary-fg': 'var(--primary-foreground)',
      'fab-primary-hover-bg': 'var(--primary)',
      'fab-primary-hover-fg': 'var(--primary-foreground)',
      'fab-secondary-bg': 'var(--secondary)',
      'fab-secondary-fg': 'var(--secondary-foreground)',
      'fab-secondary-hover-bg': 'var(--secondary)',
      'fab-secondary-hover-fg': 'var(--secondary-foreground)',
      'fab-error-bg': 'var(--destructive)',
      'fab-error-fg': 'var(--destructive-foreground)',
      'fab-error-hover-bg': 'var(--destructive)',
      'fab-error-hover-fg': 'var(--destructive-foreground)',
      'audio-chip-radius': '0px',
      'audio-chip-bg': 'transparent',
      'audio-chip-border': 'rgba(255, 255, 255, 0.4)',
      'audio-chip-foreground': 'var(--foreground)',
      'audio-chip-icon': 'var(--foreground)',
      'audio-chip-shadow': 'none',
      'audio-chip-shadow-hover': 'none',
      'video-chip-radius': '0px',
      'video-chip-bg': 'transparent',
      'video-chip-border': 'rgba(255, 255, 255, 0.25)',
      'video-chip-foreground': 'var(--foreground)',
      'video-chip-icon': 'var(--foreground)',
      'video-chip-shadow': 'none',
      'video-chip-shadow-hover': 'none',
      'audio-control-radius': '0px',
      'audio-control-border': 'rgba(255, 255, 255, 0.4)',
      'audio-control-bg': 'rgba(0, 0, 0, 0.6)',
      'audio-control-foreground': 'var(--foreground)',
      'audio-control-shadow': '0 0 0 1px rgba(255, 255, 255, 0.2)',
      'audio-control-shadow-focus': '0 0 0 1px rgba(255, 255, 255, 0.35)',
      /* Chip & rating shadows */
      'chip-shadow': 'none',
      'chip-shadow-hover': 'var(--shadow-hard-hover)',
      'rating-chip-shadow': 'none',
      'rating-chip-shadow-hover': 'var(--shadow-hard-hover)',
      'status-chip-max-width': '140px',
      'rating-chip-max-width': '120px',
      'nav-hover-style': 'flat-highlight',
      'shadow-soft': '0 8px 32px rgba(0, 0, 0, 0.4)',
      'shadow-hard': '0 12px 48px rgba(0, 0, 0, 0.6)',
      'shadow-hard-hover': '0 16px 64px rgba(0, 0, 0, 0.8)',
      'transition-smooth': 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
      'nav-border': '1px solid rgba(255, 255, 255, 0.08)',
      'nav-shadow': '0 12px 40px rgba(0, 0, 0, 0.45)',
      'nav-item-border': '1px solid rgba(255, 255, 255, 0.08)',
      'nav-item-border-selected': '1px solid rgba(94, 106, 210, 0.6)',
      'nav-item-bg': 'rgba(255, 255, 255, 0.02)',
      'nav-item-bg-selected': 'rgba(94, 106, 210, 0.2)',
      'nav-item-bg-hover': 'rgba(255, 255, 255, 0.06)',
      'nav-item-shadow': 'none',
      'nav-item-shadow-selected': '0 8px 24px rgba(0, 0, 0, 0.35)',
      'nav-item-shadow-hover': '0 8px 24px rgba(0, 0, 0, 0.25)',
      'nav-item-transform': 'translate(0, 0)',
      'nav-item-transform-hover': 'translate(0, 0)',
      'transition-bouncy': 'cubic-bezier(0.4, 0, 0.2, 1)',
      'card-hover-transform': 'translateY(-2px)',
      'nav-item-text-selected': '#F3F4FF',
    },
    dark: {
      'font-body': "'Plus Jakarta Sans'",
      'font-display': "'Plus Jakarta Sans'",
      background: '240 10% 3.9%',
      foreground: '0 0% 98%',
      card: '240 10% 3.9%',
      'card-foreground': '0 0% 98%',
      popover: '240 10% 3.9%',
      'popover-foreground': '0 0% 98%',
      primary: '235 56% 59%',
      'primary-foreground': '0 0% 100%',
      secondary: '142 72% 45%',
      'secondary-foreground': '0 0% 10%',
      muted: '240 3.7% 15.9%',
      'muted-foreground': '240 5% 64.9%',
      accent: '38 92% 55%',
      'accent-foreground': '0 0% 10%',
      destructive: '0 72% 50%',
      'destructive-foreground': '0 0% 98%',
      'success': '142 60% 45%',
      'success-foreground': '0 0% 98%',
      'warning': '38 90% 55%',
      'warning-foreground': '0 0% 10%',
      'info': '200 85% 55%',
      'info-foreground': '0 0% 10%',
      border: '240 3.7% 15.9%',
      'border-strong': '240 5% 30%',
      input: '240 3.7% 15.9%',
      'input-border': '240 3.7% 15.9%',
      'input-border-hover': '235 56% 59%',
      ring: '235 56% 59%',
      radius: '0.125rem', // 2px
      'radius-ui': '2px',
      'radius-input': '2px',
      'radius-thumb': '2px',
      'border-weight': '1px',
      'nav-radius': '0px',
      'action-bar-gap': '6px',
      'action-bar-gap-compact': '6px',
      'action-bar-padding-y': '8px',
      'action-bar-padding-x': '0px',
      'action-bar-foreground': '0 0% 98%',
      'action-bar-border': '240 3.7% 15.9%',
      'action-bar-hover-border': '240 5% 30%',
      'action-bar-disabled-foreground': '240 5% 64.9%',
      'fab-primary-bg': 'var(--primary)',
      'fab-primary-fg': 'var(--primary-foreground)',
      'fab-primary-hover-bg': 'var(--primary)',
      'fab-primary-hover-fg': 'var(--primary-foreground)',
      'fab-secondary-bg': 'var(--secondary)',
      'fab-secondary-fg': 'var(--secondary-foreground)',
      'fab-secondary-hover-bg': 'var(--secondary)',
      'fab-secondary-hover-fg': 'var(--secondary-foreground)',
      'fab-error-bg': 'var(--destructive)',
      'fab-error-fg': 'var(--destructive-foreground)',
      'fab-error-hover-bg': 'var(--destructive)',
      'fab-error-hover-fg': 'var(--destructive-foreground)',
      'audio-chip-radius': '0px',
      'audio-chip-bg': 'transparent',
      'audio-chip-border': 'rgba(255, 255, 255, 0.4)',
      'audio-chip-foreground': 'var(--foreground)',
      'audio-chip-icon': 'var(--foreground)',
      'audio-chip-shadow': 'none',
      'audio-chip-shadow-hover': 'none',
      'video-chip-radius': '0px',
      'video-chip-bg': 'transparent',
      'video-chip-border': 'rgba(255, 255, 255, 0.25)',
      'video-chip-foreground': 'var(--foreground)',
      'video-chip-icon': 'var(--foreground)',
      'video-chip-shadow': 'none',
      'video-chip-shadow-hover': 'none',
      'audio-control-radius': '0px',
      'audio-control-border': 'rgba(255, 255, 255, 0.4)',
      'audio-control-bg': 'rgba(0, 0, 0, 0.6)',
      'audio-control-foreground': 'var(--foreground)',
      'audio-control-shadow': '0 0 0 1px rgba(255, 255, 255, 0.2)',
      'audio-control-shadow-focus': '0 0 0 1px rgba(255, 255, 255, 0.35)',
      /* Chip & rating shadows */
      'chip-shadow': 'none',
      'chip-shadow-hover': '0 8px 24px rgba(0,0,0,0.35)',
      'rating-chip-shadow': 'none',
      'rating-chip-shadow-hover': '0 8px 24px rgba(0,0,0,0.35)',
      'status-chip-max-width': '140px',
      'rating-chip-max-width': '120px',
      'nav-hover-style': 'flat-highlight',
      'shadow-soft': '0 8px 32px rgba(0, 0, 0, 0.4)',
      'shadow-hard': '0 12px 48px rgba(0, 0, 0, 0.6)',
      'shadow-hard-hover': '0 16px 64px rgba(0, 0, 0, 0.8)',
      'transition-smooth': 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
      'nav-border': '1px solid rgba(255, 255, 255, 0.08)',
      'nav-shadow': '0 12px 40px rgba(0, 0, 0, 0.45)',
      'nav-item-border': '1px solid rgba(255, 255, 255, 0.08)',
      'nav-item-border-selected': '1px solid rgba(94, 106, 210, 0.6)',
      'nav-item-bg': 'rgba(255, 255, 255, 0.02)',
      'nav-item-bg-selected': 'rgba(94, 106, 210, 0.2)',
      'nav-item-bg-hover': 'rgba(255, 255, 255, 0.06)',
      'nav-item-shadow': 'none',
      'nav-item-shadow-selected': '0 8px 24px rgba(0, 0, 0, 0.35)',
      'nav-item-shadow-hover': '0 8px 24px rgba(0, 0, 0, 0.25)',
      'nav-item-transform': 'translate(0, 0)',
      'nav-item-transform-hover': 'translate(0, 0)',
      'transition-bouncy': 'cubic-bezier(0.4, 0, 0.2, 1)',
      'card-hover-transform': 'translateY(-2px)',
      'nav-item-text-selected': '#F3F4FF',
    },
  },
};
