import React from 'react';
import { ThemeDefinition } from './types';

export const neumorphicTheme: ThemeDefinition = {
  id: 'neumorphic',
  name: 'Neumorphic (Soft)',
  description: 'Soft UI with inner and outer shadows for a tactile feel.',
  layoutMode: 'top-nav',
  preview: React.createElement('div', {
    key: 'preview-root',
    style: {
      padding: '20px',
      borderRadius: '12px',
      backgroundColor: '#e0e5ec',
      boxShadow: '9px 9px 16px rgba(163, 177, 198, 0.6), -9px -9px 16px rgba(255, 255, 255, 0.5)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '100%',
      minHeight: 80,
    }
  }, [
    React.createElement('div', {
      key: 'b1',
      style: {
        width: 44,
        height: 44,
        borderRadius: '9999px',
        boxShadow: 'inset 6px 6px 10px rgba(163, 177, 198, 0.6), inset -6px -6px 10px rgba(255, 255, 255, 0.5)',
      }
    }),
    React.createElement('div', {
      key: 'b2',
      style: {
        width: 90,
        height: 16,
        borderRadius: '9999px',
        boxShadow: '9px 9px 16px rgba(163, 177, 198, 0.6), -9px -9px 16px rgba(255, 255, 255, 0.5)',
      }
    })
  ]),
  tokens: {
    light: {
      'font-body': "'DM Sans'",
      'font-display': "'DM Sans'",
      background: '210 20% 90%',
      foreground: '210 10% 20%',
      card: '210 20% 90%',
      'card-foreground': '210 10% 20%',
      popover: '210 20% 90%',
      'popover-foreground': '210 10% 20%',
      primary: '210 20% 20%',
      'primary-foreground': '210 20% 98%',
      secondary: '210 10% 85%',
      'secondary-foreground': '210 10% 20%',
      muted: '210 10% 88%',
      'muted-foreground': '210 10% 45%',
      accent: '210 20% 85%',
      'accent-foreground': '210 10% 20%',
      destructive: '0 80% 60%',
      'destructive-foreground': '210 20% 98%',
      'success': '142 50% 42%',
      'success-foreground': '0 0% 98%',
      'warning': '38 78% 52%',
      'warning-foreground': '0 0% 10%',
      'info': '210 68% 48%',
      'info-foreground': '0 0% 98%',
      border: '210 10% 85%',
      'border-strong': '210 10% 80%',
      input: '210 20% 90%',
      'input-border': 'transparent',
      'input-border-hover': 'transparent',
      ring: '210 20% 20%',
      radius: '2rem',
      'radius-ui': '16px',
      'radius-input': '16px',
      'radius-thumb': '16px',
      'border-weight': '0px',
      'nav-radius': '16px',
      'action-bar-gap': '8px',
      'action-bar-gap-compact': '6px',
      'action-bar-padding-y': '8px',
      'action-bar-padding-x': '0px',
      'action-bar-foreground': '210 10% 20%',
      'action-bar-border': '210 10% 85%',
      'action-bar-hover-border': '210 10% 80%',
      'action-bar-disabled-foreground': '210 10% 45%',
      'fab-primary-bg': 'var(--primary)',
      'fab-primary-fg': 'var(--primary-foreground)',
      'fab-primary-hover-bg': 'var(--primary)',
      'fab-primary-hover-fg': 'var(--primary-foreground)',
      'fab-secondary-bg': 'var(--secondary)',
      'fab-secondary-fg': 'var(--secondary-foreground)',
      'fab-secondary-hover-bg': 'var(--secondary)',
      'fab-secondary-hover-fg': 'var(--secondary-foreground)',
      'fab-error-bg': 'var(--destructive)',
      'fab-error-fg': 'var(--destructive-foreground)',
      'fab-error-hover-bg': 'var(--destructive)',
      'fab-error-hover-fg': 'var(--destructive-foreground)',
      'audio-chip-radius': 'var(--radius-ui)',
      'audio-chip-bg': 'transparent',
      'audio-chip-border': 'transparent',
      'audio-chip-foreground': 'var(--foreground)',
      'audio-chip-icon': 'var(--foreground)',
      'audio-chip-shadow': 'var(--shadow-soft)',
      'audio-chip-shadow-hover': 'var(--shadow-hard)',
      'video-chip-radius': 'var(--radius-ui)',
      'video-chip-bg': 'transparent',
      'video-chip-border': 'transparent',
      'video-chip-foreground': 'var(--foreground)',
      'video-chip-icon': 'var(--foreground)',
      'video-chip-shadow': 'var(--shadow-soft)',
      'video-chip-shadow-hover': 'var(--shadow-hard)',
      'audio-control-radius': 'var(--radius-ui)',
      'audio-control-border': 'transparent',
      'audio-control-bg': 'var(--input)',
      'audio-control-foreground': 'var(--foreground)',
      'audio-control-shadow': 'var(--shadow-input-rest)',
      'audio-control-shadow-focus': 'var(--shadow-input-focus)',
      'nav-hover-style': 'inset-glow',
      shadow: '0 0% 0%',
      'shadow-soft': '8px 8px 16px #bebebe, -8px -8px 16px #ffffff',
      'shadow-hard': '12px 12px 24px #bebebe, -12px -12px 24px #ffffff',
      'shadow-hard-hover': '16px 16px 32px #bebebe, -16px -16px 32px #ffffff',
      'shadow-hard-active': '4px 4px 8px #bebebe, -4px -4px 8px #ffffff',
      'transition-bouncy': 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
      'card-hover-transform': 'scale(1.02)',
      'card-hover-shadow': '20px 20px 60px #bebebe, -20px -20px 60px #ffffff',
      'shadow-input-rest': 'inset 4px 4px 8px #bebebe, inset -4px -4px 8px #ffffff',
      'shadow-input-focus': 'inset 6px 6px 12px #bebebe, inset -6px -6px 12px #ffffff',
      'neumo-breathe': 'neumo-breathe 3s ease-in-out infinite',
    },
    dark: {
      'font-body': "'DM Sans'",
      'font-display': "'DM Sans'",
      background: '210 20% 10%',
      foreground: '210 10% 90%',
      card: '210 20% 10%',
      'card-foreground': '210 10% 90%',
      popover: '210 20% 10%',
      'popover-foreground': '210 10% 90%',
      primary: '210 20% 90%',
      'primary-foreground': '210 20% 10%',
      secondary: '210 10% 15%',
      'secondary-foreground': '210 10% 90%',
      muted: '210 10% 12%',
      'muted-foreground': '210 10% 60%',
      accent: '210 20% 15%',
      'accent-foreground': '210 10% 90%',
      destructive: '0 60% 40%',
      'destructive-foreground': '210 20% 98%',
      'success': '142 45% 42%',
      'success-foreground': '210 10% 90%',
      'warning': '38 72% 52%',
      'warning-foreground': '0 0% 10%',
      'info': '210 60% 52%',
      'info-foreground': '210 10% 90%',
      border: '210 10% 15%',
      'border-strong': '210 10% 20%',
      input: '210 20% 10%',
      'input-border': 'transparent',
      'input-border-hover': 'transparent',
      ring: '210 20% 90%',
      radius: '2rem',
      'radius-ui': '16px',
      'radius-input': '16px',
      'radius-thumb': '16px',
      'border-weight': '0px',
      'nav-radius': '16px',
      'action-bar-gap': '8px',
      'action-bar-gap-compact': '6px',
      'action-bar-padding-y': '8px',
      'action-bar-padding-x': '0px',
      'action-bar-foreground': '210 10% 90%',
      'action-bar-border': '210 10% 15%',
      'action-bar-hover-border': '210 10% 20%',
      'action-bar-disabled-foreground': '210 10% 60%',
      'fab-primary-bg': 'var(--primary)',
      'fab-primary-fg': 'var(--primary-foreground)',
      'fab-primary-hover-bg': 'var(--primary)',
      'fab-primary-hover-fg': 'var(--primary-foreground)',
      'fab-secondary-bg': 'var(--secondary)',
      'fab-secondary-fg': 'var(--secondary-foreground)',
      'fab-secondary-hover-bg': 'var(--secondary)',
      'fab-secondary-hover-fg': 'var(--secondary-foreground)',
      'fab-error-bg': 'var(--destructive)',
      'fab-error-fg': 'var(--destructive-foreground)',
      'fab-error-hover-bg': 'var(--destructive)',
      'fab-error-hover-fg': 'var(--destructive-foreground)',
      'audio-chip-radius': 'var(--radius-ui)',
      'audio-chip-bg': 'transparent',
      'audio-chip-border': 'transparent',
      'audio-chip-foreground': 'var(--foreground)',
      'audio-chip-icon': 'var(--foreground)',
      'audio-chip-shadow': 'var(--shadow-soft)',
      'audio-chip-shadow-hover': 'var(--shadow-hard)',
      'video-chip-radius': 'var(--radius-ui)',
      'video-chip-bg': 'transparent',
      'video-chip-border': 'transparent',
      'video-chip-foreground': 'var(--foreground)',
      'video-chip-icon': 'var(--foreground)',
      'video-chip-shadow': 'var(--shadow-soft)',
      'video-chip-shadow-hover': 'var(--shadow-hard)',
      'audio-control-radius': 'var(--radius-ui)',
      'audio-control-border': 'transparent',
      'audio-control-bg': 'var(--input)',
      'audio-control-foreground': 'var(--foreground)',
      'audio-control-shadow': 'var(--shadow-input-rest)',
      'audio-control-shadow-focus': 'var(--shadow-input-focus)',
      /* Chip & rating shadows */
      'chip-shadow': 'var(--shadow-input-rest)',
      'chip-shadow-hover': 'var(--shadow-input-rest)',
      'rating-chip-shadow': 'var(--shadow-input-rest)',
      'rating-chip-shadow-hover': 'var(--shadow-input-rest)',
      'status-chip-max-width': '140px',
      'rating-chip-max-width': '120px',
      'nav-hover-style': 'inset-glow',
      shadow: '0 0% 0%',
      'shadow-soft': '8px 8px 16px #0a0a0a, -8px -8px 16px #1e1e1e',
      'shadow-hard': '12px 12px 24px #0a0a0a, -12px -12px 24px #1e1e1e',
      'shadow-hard-hover': '16px 16px 32px #0a0a0a, -16px -16px 32px #1e1e1e',
      'shadow-hard-active': '4px 4px 8px #0a0a0a, -4px -4px 8px #1e1e1e',
      'transition-bouncy': 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
      'card-hover-transform': 'scale(1.02)',
      'card-hover-shadow': '20px 20px 60px #0a0a0a, -20px -20px 60px #1e1e1e',
      'shadow-input-rest': 'inset 4px 4px 8px #0a0a0a, inset -4px -4px 8px #1e1e1e',
      'shadow-input-focus': 'inset 6px 6px 12px #0a0a0a, inset -6px -6px 12px #1e1e1e',
      'neumo-breathe': 'neumo-breathe-dark 3s ease-in-out infinite',
    },
  },
};
