import React from 'react';
import { ThemeDefinition } from './types';

export const playfulTheme: ThemeDefinition = {
  id: 'playful',
  name: 'Playful (Classic)',
  description: 'Bold colors, rounded corners, and expressive shadows.',
  layoutMode: 'sidebar',
  layout: {
    desktop: {
      navPlacement: 'sidebar',
      headerFrameMode: 'inset',
      mobileHeaderInset: false,
      showHeaderToggleOnMobile: false,
      showDesktopNavItems: false,
      showStorageHeaderWidget: true,
      headerVersionPlacement: 'hidden',
      headerTitleInset: '0px',
      headerToggleMode: 'collapse',
      headerToggleWidth: '57px',
      headerToggleHeight: '40px',
      headerToggleRadius: 'var(--radius-ui)',
      headerToggleColor: 'inherit',
      headerUpdateIndicatorMode: 'playful',
      headerBackground: 'var(--card, #fffdf5)',
      headerBorder: 'var(--appbar-border)',
      headerBorderBottom: 'var(--appbar-border)',
      headerPattern: 'var(--appbar-pattern)',
      headerBackdropFilter: 'none',
      headerBorderRadius: 'var(--radius-ui)',
      headerMenuRadius: 'var(--radius-ui)',
      headerMenuBorder: '2px solid var(--border-strong)',
      headerMenuBackground: 'var(--card)',
      headerMenuShadow: 'none',
      shellBackground: 'linear-gradient(180deg, var(--card) 0%, var(--background) 55%, var(--background) 100%)',
      mainPadding: 'calc(80px + var(--shell-gap)) var(--shell-gap) var(--shell-gap) calc(var(--nav-width) + var(--shell-gap) * 2)',
      mainMarginTop: '0px',
      contentPadding: '10px 8px',
      contentMaxWidth: 'none',
      contentMarginInline: '0px',
      contentFrameBackground: 'var(--card)',
      contentFrameBorder: '2px solid var(--foreground)',
      contentFrameRadius: 'var(--radius-ui)',
      contentFrameShadow: 'var(--shadow-soft)',
    },
    mobile: {
      navPlacement: 'sidebar',
      headerFrameMode: 'inset',
      mobileHeaderInset: true,
      showHeaderToggleOnMobile: false,
      showDesktopNavItems: false,
      showStorageHeaderWidget: true,
      headerVersionPlacement: 'mobile',
      headerTitleInset: '0px',
      headerToggleMode: 'collapse',
      headerToggleWidth: '44px',
      headerToggleHeight: '44px',
      headerToggleRadius: 'var(--radius-ui)',
      headerToggleColor: 'inherit',
      headerUpdateIndicatorMode: 'playful',
      headerBackground: 'var(--card, #fffdf5)',
      headerBorder: 'var(--appbar-border)',
      headerBorderBottom: 'var(--appbar-border)',
      headerPattern: 'var(--appbar-pattern)',
      headerBackdropFilter: 'none',
      headerBorderRadius: 'var(--radius-ui)',
      headerMenuRadius: 'var(--radius-ui)',
      headerMenuBorder: '2px solid var(--border-strong)',
      headerMenuBackground: 'var(--card)',
      headerMenuShadow: 'none',
      shellBackground: 'linear-gradient(180deg, var(--card) 0%, var(--background) 55%, var(--background) 100%)',
      mainPadding: 'calc(64px + var(--shell-gap) * 2) 4px var(--shell-gap)',
      mainMarginTop: '0px',
      contentPadding: '8px 3px',
      contentMaxWidth: 'none',
      contentMarginInline: '0px',
      contentFrameBackground: 'var(--card)',
      contentFrameBorder: '2px solid var(--foreground)',
      contentFrameRadius: 'var(--radius-ui)',
      contentFrameShadow: 'var(--shadow-soft)',
    },
  },
  preview: React.createElement('div', {
    style: {
      padding: '20px',
      borderRadius: '12px',
      backgroundColor: '#fffdf5',
      border: '2px solid #1e293b',
      boxShadow: '4px 4px 0px 0px #1e293b',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '100%',
      minHeight: 80,
    }
  }, [
    React.createElement('div', { key: 'b1', style: { width: 44, height: 44, borderRadius: '6px', backgroundColor: '#f472b6', border: '2px solid #1e293b' } }),
    React.createElement('div', { key: 'b2', style: { width: 90, height: 16, borderRadius: '9999px', backgroundColor: '#fbbf24', border: '2px solid #1e293b' } })
  ]),
  tokens: {
    light: {
      'font-body': "'Outfit'",
      'font-display': "'Outfit'",
      background: '48 100% 98%', // #fffdf5
      foreground: '222 47% 11%', // #1e293b
      card: '0 0% 100%',
      'card-foreground': '222 47% 11%',
      popover: '0 0% 100%',
      'popover-foreground': '222 47% 11%',
      primary: '262 83% 58%', // #8b5cf6
      'primary-foreground': '0 0% 100%',
      secondary: '340 82% 70%', // #f472b6
      muted: '210 40% 96%', // #f1f5f9
      'muted-foreground': '215 16% 47%', // #64748b
      accent: '38 92% 55%',
      'accent-foreground': '0 0% 10%',
      destructive: '0 84% 60%',
      'destructive-foreground': '0 0% 100%',
      'success': '142 70% 40%',
      'success-foreground': '0 0% 100%',
      'warning': '38 92% 50%',
      'warning-foreground': '0 0% 10%',
      'info': '217 91% 55%',
      'info-foreground': '0 0% 100%',
      border: '214 32% 91%', // #e2e8f0
      'border-strong': '222 47% 11%',
      input: '0 0% 100%',
      'input-border': '214 32% 91%',
      'input-border-hover': '222 47% 11%',
      ring: '262 83% 58%',
      radius: '1.25rem',
      'radius-ui': '24px',
      'radius-input': '16px',
      'radius-thumb': '16px',
      'border-weight': '2px',
      'nav-radius': '24px',
      'action-bar-gap': '10px',
      'action-bar-gap-compact': '6px',
      'action-bar-padding-y': '8px',
      'action-bar-padding-x': '0px',
      'action-bar-foreground': '222 47% 11%',
      'action-bar-border': '214 32% 91%',
      'action-bar-hover-border': '222 47% 11%',
      'action-bar-disabled-foreground': '215 16% 47%',
      'fab-primary-bg': 'var(--primary)',
      'fab-primary-fg': 'var(--primary-foreground)',
      'fab-primary-hover-bg': 'var(--primary)',
      'fab-primary-hover-fg': 'var(--primary-foreground)',
      'fab-secondary-bg': 'var(--secondary)',
      'fab-secondary-fg': 'var(--secondary-foreground)',
      'fab-secondary-hover-bg': 'var(--secondary)',
      'fab-secondary-hover-fg': 'var(--secondary-foreground)',
      'fab-error-bg': 'var(--destructive)',
      'fab-error-fg': 'var(--destructive-foreground)',
      'fab-error-hover-bg': 'var(--destructive)',
      'fab-error-hover-fg': 'var(--destructive-foreground)',
      'nav-hover-style': 'hard-shadow',
      'audio-chip-radius': 'var(--radius-ui)',
      'audio-chip-bg': 'transparent',
      'audio-chip-border': 'var(--border-strong)',
      'audio-chip-foreground': 'var(--foreground)',
      'audio-chip-icon': 'var(--foreground)',
      'audio-chip-shadow': 'var(--shadow-hard)',
      'audio-chip-shadow-hover': 'var(--shadow-hard-hover)',
      'video-chip-radius': 'var(--radius-ui)',
      'video-chip-bg': 'transparent',
      'video-chip-border': 'var(--border-strong)',
      'video-chip-foreground': 'var(--foreground)',
      'video-chip-icon': 'var(--foreground)',
      'video-chip-shadow': 'var(--shadow-hard)',
      'video-chip-shadow-hover': 'var(--shadow-hard-hover)',
      'audio-control-radius': 'var(--radius-ui)',
      'audio-control-border': 'var(--border-strong)',
      'audio-control-bg': 'var(--input)',
      'audio-control-foreground': 'var(--foreground)',
      'audio-control-shadow': 'var(--shadow-hard)',
      'audio-control-shadow-focus': 'var(--shadow-hard-hover)',
      shadow: '222 47% 11%',
      'shadow-soft': '8px 8px 0px 0px #e2e8f0',
      'shadow-hard': '3px 3px 0px 0px #1e293b',
      'shadow-hard-hover': '4px 4px 0px 0px #1e293b',
      'shadow-hard-active': '2px 2px 0px 0px #1e293b',
      'transition-bouncy': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      'card-hover-transform': 'translate(-2px, -2px) rotate(-0.5deg)',
      'card-hover-shadow': 'var(--shadow-hard-hover)',
      'shadow-input-rest': 'none',
      'shadow-input-focus': '0 0 0 2px var(--ring)',
      'dot-grid': 'rgba(30, 41, 59, 0.12)',
      'nav-border': '2px solid var(--foreground)',
      'nav-shadow': 'var(--shadow-hard)',
      'nav-item-bg-selected': '#fbbf24', // tertiary in playful
      'nav-item-text-selected': '#1e293b',
      'nav-item-border': '2px solid var(--foreground)',
      'nav-item-border-selected': '3px solid var(--foreground)',
      'nav-item-bg': 'transparent',
      'nav-item-bg-hover': 'rgba(251, 191, 36, 0.12)',
      'nav-item-shadow': 'none',
      'nav-item-shadow-selected': '3px 3px 0px 0px #1e293b',
      'nav-item-shadow-hover': '3px 3px 0px 0px #1e293b',
      'settings-splash-shadow-hover': '6px 6px 0px 0px #fbbf24',
      'settings-splash-border': '#fbbf24',
      'chip-shadow-hover': 'none',
      'nav-item-transform': 'translate(0, 0)',
      'nav-item-transform-hover': 'translate(-2px, -2px)',
      'appbar-border': '2px solid var(--foreground)',
      'appbar-shadow': 'var(--shadow-hard)',
    },
    dark: {
      'font-body': "'Outfit'",
      'font-display': "'Outfit'",
      background: '222 47% 11%', // #0f172a
      foreground: '48 100% 98%', // #fffdf5
      card: '222 47% 11%',
      'card-foreground': '48 100% 98%',
      popover: '222 47% 11%',
      'popover-foreground': '48 100% 98%',
      primary: '258 90% 66%', // #8b5cf6
      'primary-foreground': '222 47% 11%',
      secondary: '340 82% 70%',
      muted: '222 47% 20%',
      'muted-foreground': '215 16% 70%',
      accent: '222 47% 20%',
      'accent-foreground': '0 0% 10%',
      destructive: '0 84% 40%',
      'destructive-foreground': '0 0% 100%',
      'success': '142 55% 45%',
      'success-foreground': '0 0% 10%',
      'warning': '38 85% 55%',
      'warning-foreground': '0 0% 10%',
      'info': '217 75% 65%',
      'info-foreground': '0 0% 10%',
      border: '222 47% 25%',
      'border-strong': '48 100% 98%',
      input: '222 47% 11%',
      'input-border': '222 47% 25%',
      'input-border-hover': '48 100% 98%',
      ring: '258 90% 66%',
      radius: '1.25rem',
      'radius-ui': '24px',
      'radius-input': '16px',
      'radius-thumb': '16px',
      'border-weight': '2px',
      'nav-radius': '24px',
      'action-bar-gap': '10px',
      'action-bar-gap-compact': '6px',
      'action-bar-padding-y': '8px',
      'action-bar-padding-x': '0px',
      'action-bar-foreground': '48 100% 98%',
      'action-bar-border': '222 47% 25',
      'action-bar-hover-border': '48 100% 98%',
      'action-bar-disabled-foreground': '215 16% 70%',
      'fab-primary-bg': 'var(--primary)',
      'fab-primary-fg': 'var(--primary-foreground)',
      'fab-primary-hover-bg': 'var(--primary)',
      'fab-primary-hover-fg': 'var(--primary-foreground)',
      'fab-secondary-bg': 'var(--secondary)',
      'fab-secondary-fg': 'var(--secondary-foreground)',
      'fab-secondary-hover-bg': 'var(--secondary)',
      'fab-secondary-hover-fg': 'var(--secondary-foreground)',
      'fab-error-bg': 'var(--destructive)',
      'fab-error-fg': 'var(--destructive-foreground)',
      'fab-error-hover-bg': 'var(--destructive)',
      'fab-error-hover-fg': 'var(--destructive-foreground)',
      'audio-chip-radius': 'var(--radius-ui)',
      'audio-chip-bg': 'transparent',
      'audio-chip-border': 'var(--border-strong)',
      'audio-chip-foreground': 'var(--foreground)',
      'audio-chip-icon': 'var(--foreground)',
      'audio-chip-shadow': 'var(--shadow-hard)',
      'audio-chip-shadow-hover': 'var(--shadow-hard-hover)',
      'video-chip-radius': 'var(--radius-ui)',
      'video-chip-bg': 'transparent',
      'video-chip-border': 'var(--border-strong)',
      'video-chip-foreground': 'var(--foreground)',
      'video-chip-icon': 'var(--foreground)',
      'video-chip-shadow': 'var(--shadow-hard)',
      'video-chip-shadow-hover': 'var(--shadow-hard-hover)',
      'audio-control-radius': 'var(--radius-ui)',
      'audio-control-border': 'var(--border-strong)',
      'audio-control-bg': 'var(--input)',
      'audio-control-foreground': 'var(--foreground)',
      'audio-control-shadow': 'var(--shadow-hard)',
      'audio-control-shadow-focus': 'var(--shadow-hard-hover)',
      /* Chip and rating shadows */
      'chip-shadow': 'none',
      'chip-shadow-hover': 'none',
      'rating-chip-shadow': 'none',
      'rating-chip-shadow-hover': 'none',
      'status-chip-max-width': '140px',
      'rating-chip-max-width': '120px',
      'nav-hover-style': 'hard-shadow',
      shadow: '48 100% 98%',
      'shadow-soft': '8px 8px 0px 0px rgba(0,0,0,0.3)',
      'shadow-hard': '3px 3px 0px 0px #fffdf5',
      'shadow-hard-hover': '4px 4px 0px 0px #fffdf5',
      'shadow-hard-active': '2px 2px 0px 0px #fffdf5',
      'transition-bouncy': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      'card-hover-transform': 'translate(-2px, -2px) rotate(-0.5deg)',
      'card-hover-shadow': 'var(--shadow-hard-hover)',
      'shadow-input-rest': 'none',
      'shadow-input-focus': '0 0 0 2px var(--ring)',
      'dot-grid': 'rgba(255, 255, 255, 0.1)',
      'nav-border': '2px solid var(--foreground)',
      'nav-shadow': 'var(--shadow-hard)',
      'nav-item-bg-selected': '#fbbf24',
      'nav-item-text-selected': '#1e293b',
      'nav-item-border': '2px solid var(--foreground)',
      'nav-item-border-selected': '3px solid var(--foreground)',
      'nav-item-bg': 'transparent',
      'nav-item-bg-hover': 'rgba(255, 255, 255, 0.08)',
      'nav-item-shadow': 'none',
      'nav-item-shadow-selected': '3px 3px 0px 0px #fffdf5',
      'nav-item-shadow-hover': '3px 3px 0px 0px #fffdf5',
      'settings-splash-shadow-hover': '6px 6px 0px 0px #fbbf24',
      'settings-splash-border': '#fbbf24',
      'nav-item-transform': 'translate(0, 0)',
      'nav-item-transform-hover': 'translate(-2px, -2px)',
      'appbar-border': '2px solid var(--foreground)',
      'appbar-shadow': 'var(--shadow-hard)',
    },
  },
};
