import type {Config} from '@docusaurus/types';
// @ts-ignore canonical manifest is generated by scripts/manifest.mjs
import {manifest} from './scripts/manifest.mjs';
const sections = ['Getting Started', 'Using Youtarr', 'Operations', 'Developers', 'Project'];
const manifestNav = sections.map((label) => ({label, type: 'dropdown' as const, items: manifest.filter((item: any) => item.section === label).sort((a: any, b: any) => a.order - b.order).map((item: any) => ({label: item.title, to: `/docs/${item.slug}`}))}));
const config: Config = {
  title: 'Youtarr', tagline: 'Self-hosted YouTube archiving for your media library', url: 'https://dialmasterorg.github.io', baseUrl: '/Youtarr/', favicon: 'img/favicon.ico', organizationName: 'DialmasterOrg', projectName: 'Youtarr', trailingSlash: true,
  onBrokenLinks: 'throw', onBrokenMarkdownLinks: 'throw', onBrokenAnchors: 'throw', i18n: {defaultLocale:'en', locales:['en']},
  presets: [['classic', {docs: {path:'./.generated/docs',routeBasePath:'docs', sidebarPath:'./sidebars.ts', showLastUpdateTime:false}, blog:false, theme:{customCss:'./src/css/custom.css'}}]],
  staticDirectories: ['static', '.generated/static'],
  themeConfig: {colorMode:{defaultMode:'dark',disableSwitch:false,respectPrefersColorScheme:false}, navbar:{title:'Youtarr',logo:{alt:'Youtarr',src:'img/logo512.png',width:32,height:32},items:[...manifestNav,{label:'API',to:'/docs/api'},{type:'search',position:'right'},{href:'https://github.com/DialmasterOrg/Youtarr',label:'GitHub',position:'right'}]}, footer:{style:'dark',links:[{title:'Project',items:[{label:'GitHub',href:'https://github.com/DialmasterOrg/Youtarr'},{label:'Issues',href:'https://github.com/DialmasterOrg/Youtarr/issues'},{label:'Discord',href:'https://discord.gg/68rvWnYMtD'}]},{title:'Policies',items:[{label:'Security',to:'/docs/security'},{label:'License',to:'/docs/license'}]}],copyright:'Copyright © DialmasterOrg'}},
  plugins:[['@cmfcmf/docusaurus-search-local',{indexDocSidebarParentCategories:1,indexDocs:true,indexBlog:false,language:['en']}]],
};
export default config;
