import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
// @ts-ignore canonical manifest is generated by the repository-aware script
import {manifest} from './scripts/manifest.mjs';

const sections = ['Getting Started', 'Using Youtarr', 'Operations', 'Developers', 'Project'];
const sidebars: SidebarsConfig = {docs: sections.map((label) => ({type: 'category' as const, label, collapsed: false, items: [ ...(label === 'Getting Started' ? ['quick-start'] : []), ...manifest.filter((item: any) => item.section === label).sort((a: any, b: any) => a.order - b.order).map((item: any) => item.slug.includes('/') ? `${item.slug.split('/')[0]}/${item.id}` : item.id), ...(label === 'Developers' ? ['api'] : [])] }))};
export default sidebars;
